# Created using eduVPN build system
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: SURF.eduVPNClient
PackageVersion: 4.4
PackageLocale: en-US
Publisher: SURF
PublisherUrl: https://www.eduvpn.org/
PackageName: eduVPN Client
License: GPL-3.0
ShortDescription: Access your institute's network or the Internet using an encrypted connection.
Tags:
- vpn
- eduvpn
ReleaseNotesUrl: https://codeberg.org/eduVPN/windows/releases/tag/4.4
ManifestType: defaultLocale
ManifestVersion: 1.10.0

